### PR TITLE
 Using services like Github helps to backup code

### PR DESCRIPTION
**Pull request by Tobias-Ternent**
Using services like Github helps to backup code #151 
I've added a short paragraph about this. Not sure if you want to keep the text here, move it somewhere else, or even reject it entirely if it means keeping focus.

### CODE REVIEW

**Comment by lgatto** [comment]
I think it's nice. My only suggestion would be:

> If the remote GitHub server is unavailable, collaboration and work can continue between users, as opposed to centralized alternatives.

I find the original version very negative towards the alternatives.

**Comment by Tobias-Ternent** [comment]
I think I'm still bitter about SourceForge being up and down in the past. Even trying to link to its news item now, it's down again, quelle surprise :/ 
Bundled adware really didn't help its public relations as well.

**Comment by lgatto** [comment]
@Tobias-Ternent are you fine with me doing that little change and merging?

**Comment by Tobias-Ternent** [comment]
Yes no problem, please go ahead with the change as merge as required.

**Pull request closed without merging**
