### PR TITLE
cutting down and simplying the text, as we are again > 2500 words

### PR DESCRIPTION
**Pull request by lgatto**
@javizca I have made some modifications, mainly in the intro, to reduce the length.

### CODE REVIEW

**Comment by javizca** [comment]
Ok, thanks a lot. I will review this version today and come back to you.

**Comment by lgatto** [comment]
Ok, thanks. Either create a PR that I can merge and convert to PLoS tex. We could also have a phone/skype chat if you wish.

**Comment by javizca** [comment]
Done. I have not changed anything significant. Just typos, improvements in the language and similar things. A legend for Figure 1 is needed. I need to check if the figure needs to be included in the same document or it needs to be submitted separately.

**Comment by lgatto** [comment]
@javizca The legend is currently 

> The structure of a GitHub-based project illustrating the projects structure and the interactions with the community.

**Pull request merged**
