### PR TITLE
Jupyter Notebook containing code and output of the GitHub/PMC plot

### PR DESCRIPTION
**Pull request by tompollard**
This pull request adds a Jupyter Notebook (R kernel) containing the code and output for the "github.com references on Pubmed Central" plot at: http://computationalproteomic.blogspot.co.uk/2016/04/github-in-numbers-for-bioinformaticians.html. If everyone is happy with adding the Notebook, then we could incorporate the other plots too.

### CODE REVIEW

**Comment by tompollard** [comment]
Apologies, I think I have misattributed @ypriverol's code to @sje30...

**Comment by tompollard** [comment]
Instructions for installing the R kernel for Jupyter Notebook are at: https://github.com/IRkernel/IRkernel

**Comment by lgatto** [comment]
This is nice, but adding this to the manuscript brings us a bit far from the topic, IMHO; the paper is already very dense as it is. Do you have plans to add it to the actual manuscript?

**Comment by tompollard** [comment]
My intention was just to include the Notebook in the repo as additional content that people might find interesting. I hadn't intended to make any changes to the manuscript itself, though we could draw attention to the Notebook in the readme.

**Comment by lgatto** [comment]
That's great, indeed, thanks. May be @ypriverol could link to the notebook from his blog post to increase visibility?

**Comment by ypriverol** [comment]
@lgatto @tompollard Never use before Jupyter. Most than happy to integrate the current code on it. Would actually nice exercise. How are we planning to put this in the manuscript? How can I setup everything in my side?

**Comment by lgatto** [comment]
> How are we planning to put this in the manuscript?

Not.

**Comment by ypriverol** [comment]
@lgatto then the idea is to put in the repo the Jupyter Notebook for the follow up

**Comment by tompollard** [comment]
@ypriverol in case you are familiar with IPython Notebook, Jupyter Notebook is just the new name. Whether or not we mention the Notebook in the manuscript (I don't mind either way), I think it provides some interesting supplementary material that people might find interesting. It also we means we can refine the analysis together over time.

> How can I setup everything in my side?
1. First install Jupyter Notebook (e.g. on OSX with homebrew, run "brew install jupyter"). 
2. Next install the R Kernel, which is a little less straightforward. I don't remember the exact details, but see: https://github.com/IRkernel/IRkernel
3. Then run "jupyter notebook" at the command line in the directory containing the ipynb file.

**Comment by ypriverol** [comment]
@lgatto I will accept the current PR to make available the Jupyter file with the repo even if we will not provide a link in the manuscript. Are you OK ?

**Comment by tompollard** [comment]
@lgatto @ypriverol we could put this in a "supplementaryfiles" directory or similar to make it clear that it does not form part of the manuscript.

**Pull request merged**
