### PR TITLE
2nd batch of suggestions

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
I've finished the 2nd batch of my suggestions, started in #184 - please have a look.

### CODE REVIEW

**Comment by lgatto** [comment]
@alex-konovalov Is the ref to be added 

```
@INPROCEEDINGS{Buckheit95wavelaband,
    author = {Jonathan Buckheit and David Donoho},
    title = {WaveLab and Reproducible Research},
    booktitle = {},
    year = {1995},
    pages = {55--81},
    publisher = {Springer-Verlag}
}
```

(the URL seems to be down at the moment)

**Comment by olexandr-konovalov** [comment]
@lgatto thanks - I will rebase to resolve conflicts later tonight.

**Comment by lgatto** [comment]
Sorry for inflicting these conflicts on you. I will try to do these if you don't get time to do it.

**Comment by ypriverol** [comment]
I can have a look if you want @alex-konovalov

**Comment by olexandr-konovalov** [comment]
@ypriverol @lgatto no problem, it's only one text block. I am fixing it now.

**Comment by lgatto** [comment]
No, there's three - are you sure you are uptodate?

**Comment by olexandr-konovalov** [comment]
@lgatto I see only one, will push now - let's see what happens.

**Comment by ypriverol** [comment]
@lgatto You can be 100% sure

**Comment by lgatto** [comment]
@alex-konovalov as you prefer - I have a rebased version ready for merging #192 (currently still being checked).

**Comment by olexandr-konovalov** [comment]
@lgatto @ypriverol you're right - three blocks :) figured out and learned what I did wrong first time. Hope this is ready for the merge now.

**Comment by olexandr-konovalov** [comment]
Haven't seen #192 which now has also new citation - then I can close this one, as I've already learned my lesson:) I will close it now.

**Pull request closed without merging**
