### PR TITLE
wording changes throughout and a suggested new reference on software citation

### PR DESCRIPTION
**Pull request by danielskatz**
I've made a lot of wording changes to make the language sound more like American English.  I've also changed words from UK to US spelling, since PLOS is a US journal.  Finally, I added a reference on software citation.

### CODE REVIEW

**Comment by lgatto** [comment]
Hi @danielskatz - I looks like you have worked on the tex file. We have been working on the md file, which, eventually, is converted into tex/pdf for submission. The tex file is the first submission, that has undergone quite a bit of changes since then - am sorry for the confusion. Would you be willing to have a go at the [manuscript.md](https://github.com/ypriverol/github-paper/blob/master/document/manuscript.md) file?

**Comment by lgatto** [comment]
The Force11 reference is great - it should be added anyway.

**Comment by danielskatz** [comment]
Sorry, I feel like I've done my volunteer part already, and don't really have time to go through this again.

But here's the key parts of the diff showing the changes I made in the .tex file - I hope you can bring them into the .md file.  And I assume you can pull in the force11 reference...

Dan

168c168

## < (e.g.~for commercial software) or, better, openly shared and directly

> (e.g., for commercial software) or, better, openly shared and directly
> 175c175
> 
> ## < since they enable the organisation and sharing of programming tasks
> 
> since they enable the organization and sharing of programming tasks
> 177,178c177,178
> < features of GitHub, a popular web-based platform which offers a free and
> 
> ## < integrated environment for hosting the source code, documentation and
> 
> features of GitHub, a popular web-based platform that offers a free and
> integrated environment for hosting the source code, documentation, and
> 180c180
> 
> ## < private repositories. GitHub relies, at its core, on the well-known and
> 
> private repositories. At its core, GitHub relies on the well-known and
> 185c185
> 
> ## < environment, often coined as social coding platform, with the ability to
> 
> environment, often referred to as social coding platform, with the ability to
> 192,194c192,194
> < projects and increase their profile and visibility. These rules have
> < been ordered to reflect a typical development process: learning git and
> 
> ## < GitHub basics, use branches, label and tag code, track the project using
> 
> projects and increase their profile and visibility. These rules are
> ordered to reflect a typical development process: learning git and
> GitHub basics, using branches, labeling and tagging code, tracking the project using
> 197c197
> 
> ## < \subsection*{Rule 1. Structure your projects: users, organisations,
> 
> \subsection*{Rule 1. Structure your projects: users, organizations,
> 201c201
> 
> ## < Open source projects on GitHub are visible to everyone, but write
> 
> Public repositories for open source projects on GitHub are visible to everyone, but write
> 203,204c203,204
> < to explicitly be granted. On the other hand, everyone with a GitHub
> 
> ## < account can fork any public project and start developing in one's own
> 
> to be granted explicitly. On the other hand, anyone with a GitHub
> account can fork any public project and start developing in their own
> 206,208c206,208
> < develop and test novel features into existing code and offers the
> < possibility to merge novel features back the into the main project,
> 
> ## < thereby becoming a contributor. Structuring your projects allows to
> 
> develop and test novel features in existing code and offers the
> possibility of merging that work back the into the main project,
> thereby becoming a contributor. Structuring your projects allows you to
> 210c210
> 
> ## < and organisations. Users are the keystone of GitHub, as for any other
> 
> and organizations. Users are the central element of GitHub, as in any other
> 213,214c213,214
> < information including name, e-mail address, image and webpage. To stay
> 
> ## < up to date with the activity of other users one can \emph{follow} their
> 
> information including name, e-mail address, image, and webpage. To stay
> up to date with the activity of other users, one can \emph{follow} their
> 218c218
> 
> ## < a larger organisation. GitHub organisations are a great way to manage
> 
> a larger organization. GitHub organizations are a great way to manage
> 223c223
> 
> ## < projects and organisations you are working in, including a list of the
> 
> projects and organizations you are working in, including a list of the
> 225c225
> 
> ## < shortened term is \emph{repo}) are versioned directories or dedicated
> 
> short term is \emph{repo}) are versioned directories or dedicated
> 227,228c227,228
> < an organisation or can belong to particular users. Users can usually
> 
> ## < keep code, text files, images and small data files inside a repo. And
> 
> an organization or can belong to particular users. Users can usually
> keep code, text files, images, and small data files inside a repo. And
> 231,234c231,234
> < and manuscripts (see for example the repository for this manuscipt at
> < https://github.com/ypriverol/github-paper), or other file types in your
> < projects. Note that until recently, GitHub was lacking support for
> 
> ## < storing large files (\textgreater{}100 MB), a issue that has been
> 
> and manuscripts (see for example the repository for this manuscript at
> \url{https://github.com/ypriverol/github-paper}), or other file types in your
> projects. Note that until recently, GitHub lacked support for
> storing large files (\textgreater{}100 MB), but this has been
> 247,255c247,255
> < The cornerstone of GitHub is the distributed version control system git.
> < Every change, from fixing a typo to a complete redesign of the software
> < is controlled by versions, so called revisions. While beginners may
> < consider the learning curve of Git steep, many introductory and detailed
> < tutorials are available. A revision can be considered as a
> < \emph{snapshot} (version) of a file system. Git is remarkably effective
> < in archiving the complete history of a project (all revisions) by,
> < amongst other things, storing only the differences among them. To create
> 
> ## < a new revision, the set of changes introduced (e.g.~new, deleted or
> 
> The backbone of GitHub is the distributed version control system git.
> Every change, from fixing a typo to a complete redesign of the software,
> is stored as a version, called a revision. While beginners may
> find the learning curve for git steep, many introductory and detailed
> tutorials are available. A revision can be viewed as a
> \emph{snapshot} (version) of a file system. Git is remarkably efficient
> at archiving the complete history of a project (all revisions) by,
> among other things, storing only the differences among them. To create
> a new revision, the set of changes introduced (e.g., new, deleted, or
> 257c257
> 
> ## < ``commit often, as most as you can, perfection later'', one can keep
> 
> ``commit often, as much as you can, perfect later'', one can keep
> 264,265c264,265
> < Concurrent development including commits to the same repository can be
> 
> ## < organised using several common approaches. The most common way is to use
> 
> Concurrent development, including multiple commits to the same repository, can be
> organized using several common approaches. The most common way is to use
> 267,269c267,269
> < development is often performed on a development branch and stable
> < versions e.g.~those used for a software release, are kept in a master
> 
> ## < branch. In practice, developers work on one or several features or
> 
> development is often performed on a development branch, and stable
> versions, e.g., those used for a software release, are kept in a master
> branch. In practice, developers often work concurrently on one or several features or
> 272c272
> 
> ## < is complete and none of the tests fail (see Rule 6) new features can be
> 
> is complete and none of the tests fail (see Rule 6), new features can be
> 277c277
> 
> ## < always enabling to react or adapt to the changes in the code. In
> 
> always enabling one to react or adapt to the changes in the code. In
> 280,282c280,282
> < project forward. \emph{Forking} a repository and providing \emph{pull
> < requests} constitute an easy way for collaboration inside and over
> 
> ## < organisations boundaries. A user that forks a repository creates a copy
> 
> project forward. \emph{Forking} a repository and using \emph{pull
> requests} constitutes an easy method for collaboration inside and over
> organizational boundaries. A user who forks a repository creates a copy
> 287,288c287,288
> < an increased code quality. Once a pull request gets accepted, typically
> 
> ## < it gets merged into the development branch.
> 
> increased code quality. Once a pull request is accepted, it typically
> is merged into the development branch.
> 293,295c293,295
> < Tags offer the possibility to label versions during the development
> < process, tracking its progress. Version numbering should follow semantic
> 
> ## < versioning in the form X.Y.Z, with X being the major, Y the minor and Z
> 
> Tags offer the possibility of labeling versions during the development
> process, to track its progress. Version numbering should follow semantic
> versioning in the form X.Y.Z, with X being the major, Y the minor, and Z
> 297c297
> 
> ## < as described in http://semver.org/. Correct labelling allows developers
> 
> as described in \url{http://semver.org/}. Correct labelling allows developers
> 300c300
> 
> ## < approach will also help defining a coherent software publication
> 
> approach also helps to define a coherent software publication
> 307,308c307,308
> < ready to use as soon as possible \cite{Leprevost:2014}, remain so during
> 
> ## < development, and should be well-documented and tested. In 2005, Martin
> 
> ready to use as soon as possible \cite{Leprevost:2014}, to remain so during
> development, and to be well-documented and tested. In 2005, Martin
> 318,320c318,320
> < wrong results, the so called \emph{logic errors}, where the source code
> < produces a different result compared to what one intended it to do.
> 
> ## < Then, continuous integration provides the way of automatically run all
> 
> wrong results, often known as \emph{logic errors}, where the source code
> produces a different result than what was intended.
> Continuous integration provides a way to automatically run all
> 329,330c329,330
> < to a repository, making easier to follow the basic principles of
> 
> ## < continuous integration. The GitHub web hooks allows third-party
> 
> to a repository, making it easier to follow the basic principles of
> continuous integration. The GitHub web hooks allow third-party
> 333,334c333,334
> < that a project follows rigorous software engineering processes, often
> 
> ## < associated with high quality development. It also shows that is
> 
> that a project follows rigorous software engineering processes, which are often
> associated with high quality development. They also show that the project
> 336,337c336,337
> < We suggest that all these three tasks become part of your project.
> 
> ## < Firstly, continuous integration can be achieved by \emph{Travis}
> 
> We suggest that all three of the following tasks become part of your project.
> First, continuous integration can be achieved by \emph{Travis}
> 341c341
> 
> ## < interpreter versions. Furthermore it offers notifications which allow
> 
> compiler\slash interpreter versions. In addition, it offers notifications that allow
> 344,350c344,350
> < use. Secondly, in addition to successful completion of the tests, one
> < can also demonstrate that they cover the existing code base
> < sufficiently. For this task, the integration of \emph{Codecov} is
> < recommended (https://codecov.io). Thirdly, one might consider to
> < automatically update the documentation upon code modification. This
> < implies that your projects provide comprehensive documentation so others
> 
> ## < can understand, and contribute back to them. For Python or C/C++ code,
> 
> use. Second, in addition to successfully completing the tests, one
> can also demonstrate that the tests sufficiently cover the existing code base.
> For this, integration of \emph{Codecov} (\url{https://codecov.io}) is
> recommended. Third, one might consider
> automatically updating the documentation upon code modification. This
> implies that your project provides comprehensive documentation so that others
> can understand, and contribute back to it. For Python or C/C++ code,
> 352,354c352,354
> < (http://sphinx-doc.org/) and subsequently integrated into GitHub using
> < ``Read the Docs'' (https://readthedocs.org/). All of these platforms
> 
> ## < will create reports and badges (also called shields) for the projects
> 
> (\url{http://sphinx-doc.org/}) and subsequently integrated into GitHub using
> ``Read the Docs'' (\url{https://readthedocs.org/}). These tools
> create reports and badges (also called shields) for the projects
> 367,370c367,370
> < put in promoting collaboration, providing context by using
> < cross-references, and an excellent text formatting for each issue: (i) a
> < title and description, (ii) colour-coded labels help to categorise and
> 
> ## < filter issues, (iii) milestones act as a container for issues,(iv) one
> 
> in promoting collaboration, providing context by using
> cross-references.  Issues also have very clear formatting: (i) a
> title and description, (ii) color-coded labels help to categorize and
> filter issues, (iii) milestones act as a container for issues, (iv) an
> 373,375c373,375
> < aspect is its simplicity. For instance, it does not require to fill
> < lengthy forms including every piece of information that might be
> 
> ## < valuable to reproduce the bug. It only requires to give the title and
> 
> aspect of issues is its simplicity. For instance, it does not require someone to fill
> out lengthy forms that include every piece of information that might be
> valuable to reproduce the bug. It only requires someone to give the title and
> 377,379c377,379
> < they can simply request it in a comment. GitHub issues are then more
> < dynamic and pose a lower barrier for users to report bugs and request
> 
> ## < features. A well-organised and tagged issue tracker will help upcoming
> 
> they can simply request it in a comment. GitHub issues are thus more
> dynamic and pose a lower barrier-to-entry for users to report bugs and request
> features. A well-organized and tagged issue tracker will help upcoming
> 391,394c391,394
> < other types of scientific outputs such as datasets \cite{Vizcaino:2014}
> < or training materials (for example \cite{Ahmadia_2015_27353}). The main
> < motivation behind this is to give scientists a better credit for their
> 
> ## < work \cite{NatBiotechEditorial:2009}, enabling at the same time a better
> 
> other types of scientific outputs such as datasets \cite{Vizcaino:2014},
> training materials (for example \cite{Ahmadia_2015_27353}), and software. The main
> motivation behind this is to give scientists better credit for their
> work \cite{NatBiotechEditorial:2009,force11-scwg}, simultaneously enabling a better
> 396c396
> 
> ## < normally evolves at a different speed than what is published in the
> 
> normally evolves at a different speed than text published in the
> 401,403c401,403
> < (https://zenodo.org/). The procedure is simple (see
> < https://guides.GitHub.com/activities/citable-code/) and, by default,
> 
> ## < Zenodo takes an archive of a repository each time a new release is
> 
> (\url{https://zenodo.org/}). The procedure is simple (see
> \url{https://guides.GitHub.com/activities/citable-code/}) and, by default,
> Zenodo creates an archive of a repository each time a new release is
> 410,414c410,415
> < providing openly the software, the datasets and the process leading to
> < interpretable results that are used in a particular study. One should
> < always highlight as much as possible in publications that the code is
> < freely available in, for example, GitHub, together with any other
> 
> ## < relevant piece of information that may have been deposited. In our
> 
> openly providing the software, the datasets, and the process leading to
> interpretable results that was used in a particular study. As much as possible,
> publications should highlight that the code is
> freely available in, for example, GitHub, and cite the DOI of the archived version
> of the code that was used, together with any other
> relevant information that may have been deposited. In our
> 418c419
> 
> ## < manuscript review process, increasing the confidence of your results. On
> 
> manuscript review process, increasing their confidence in your results. On
> 422c423
> 
> ## < one must have in mind that the availability of a public repository with
> 
> one must keep in mind that the availability of a public repository with
> 424,425c425,426
> < it needs to have an appropriate license
> 
> ## < (http://opensource.org/licenses/).
> 
> it also needs to have an appropriate license
> (\url{http://opensource.org/licenses/}).
> 431c432
> 
> ## < Additional steps can be done to boost the visibility of a organisation.
> 
> Additional steps can boost the visibility of a organization.
> 433,434c434,435
> < hosts for free without the need for a server or database. GitHub users
> 
> ## < can create and host blog websites, help pages, manuals, tutorials and
> 
> hosts for free without the need for a separate server or database. GitHub users
> can create and host blog websites, help pages, manuals, tutorials, and
> 436c437
> 
> ## < powerful static site generator called Jekyll (https://jekyllrb.com) that
> 
> powerful static site generator called Jekyll (\url{https://jekyllrb.com}) that
> 438,441c439,442
> < (http://getbootstrap.com/) or Disqus (https://disqus.com/), to support
> < and moderate comments. In addition, GitHub also provides mechanisms for
> < real-time communication called Gitter (http://gitter.im). Gitter is a
> 
> ## < GitHub-based chat tool (in limited beta at the time of writing) which
> 
> (\url{http://getbootstrap.com/}) or Disqus (\url{https://disqus.com/}), to support
> and moderate comments. In addition, GitHub also provides a mechanism for
> real-time communication called Gitter (\url{http://gitter.im}). Gitter is a
> GitHub-based chat tool (in limited beta at the time of writing) that
> 443,444c444,445
> < inherits the shape of the social groups operating around GitHub
> 
> ## < repositories, organisations, and issues. It relies on the identity
> 
> inherits the network of social groups operating around GitHub
> repositories, organizations, and issues. It relies on the identity
> 446,448c447,449
> < public and private repositories. From within a Gitter chat, members can
> < reference issues, comments, or pull-requests. A different service is
> 
> ## < Gist (https://gist.github.com), which represents a unique way to share
> 
> public and private repositories. Within a Gitter chat, members can
> reference issues, comments, or pull requests. A different service is
> Gist (\url{https://gist.github.com}), which represents a unique way to share
> 450,451c451,452
> < applications. Gist can be generated in two different ways: public
> 
> ## < \emph{gists}, that can be browsed and searched, and secret gists that
> 
> applications. Gists can be generated in two different ways: public
> \emph{gists} that can be browsed and searched, and secret gists that
> 453,454c454,455
> < (https://gist.github.com/discover). One of the main features of Gist is
> 
> ## < the possibility to embed code snippets in other applications, enabling
> 
> (\url{https://gist.github.com/discover}). One of the main features of Gist is
> the ability to embed code snippets in other applications, enabling
> 460c461
> 
> ## < One of the main tasks of scientists is to actively follow the
> 
> One of scientists' main tasks is to actively follow the
> 462c463
> 
> ## < revise publicly available (e.g.~open source) projects and code that can
> 
> revise publicly available (e.g., open source) projects and code that might
> 464c465
> 
> ## < much as possible from your peers and keep up-to-date with all the
> 
> much as possible from your peers, and keep up-to-date with all the
> 473,474c474,475
> < to get started as soon as possible. As in any other topic, a learning
> 
> ## < curve is required for beginners. However, we anticipate the reward will
> 
> get started as soon as possible. As with any other topic, there is a learning
> curve for beginners. However, we anticipate the reward will
> 481c482
> 
> ## < without any input from any third party organisation.
> 
> without any input from any third party organization.
> 487a489

**Comment by ypriverol** [comment]
I would do the check thanks for your support!!!

**Comment by lgatto** [comment]
Of course, I understand. Thank you for your contribution @danielskatz

**Pull request closed without merging**
