### PR TITLE
some changes in the figure

### PR DESCRIPTION
**Pull request by ypriverol**
Please @julianu and @timosachsenberg review this new proposal for the figure.

### CODE REVIEW

**Comment by julianu** [comment]
It definitely looks a bit tidier.
But for the green one a fork seems missing? And, at least for me, the distinction between the members, who directly commit and who fork is not that clear. But maybe it was in my draft neither.
Otherwise: nice!

**Comment by ypriverol** [comment]
@julianu.. agree with you .. this is only a more structured approach.  Can you work arround it to improve the missing points: forks and communications eith community.

**Comment by ypriverol** [comment]
@timosachsenberg @lgatto  Any comments in the figure.

**Comment by lgatto** [comment]
I'm fine with it. @timosachsenberg feel free to merge if you like it

**Comment by ypriverol** [comment]
@lgatto I would like to open the article for suggestions before it publication, can we twit and ask for recommendations before the publication. What do you think?

**Comment by timosachsenberg** [comment]
I like the current image much better than the last one I would suggest some changes.
In general I think the representation depends on whether we want to promote a gitflow like workflow or something simplified as shown in the image. In both cases one might think about talking about the github repository and local clones / forks (including the same repository icon)
Some other issues related to that:
1. it doesn't ideally reflect the difference between develop and master branch (e.g. the number of intermediate commits and converging of branches (aka integration of develop into master))
2. Syncing between develop and master branch ist rarely done with PRs
3. Commits are usually applied to a fork and not directly to the main repo (might depend on the development model but never to master as suggested by "anne")
4. It is not clear that syncing happens for local repositories and forks by bringing them up to date with the upstream repository. 
5. It might be interesting to show that issues can be connected to PRs (e.g. a fix for an issue or implementation of a feature)
6. interaction with the users on the right side could show text on the lines an be more "interactive" e.g. user 1 finds a bug and opens an issue, user 2 (developer) comments on it, refers to a PR. user 3 adds something to the documentation (wiki)
7. I would only use one symbol for code and commit to simplify the plot

**Comment by lgatto** [comment]
Agree in general with @timosachsenberg. Regarding points 1 - 5, while being correct, these get quite technical, and I don't think that this is the best place to explain all the details. GitHub has good documentation for that. However, point 6 is spot on. I think the various types of interactions, within the core team and with other members of the community, are the most important point.

**Comment by timosachsenberg** [comment]
@lgatto that's fine with me. I think it is a valid point that we don't want to go too much into detail on gitflow. We still might think about choosing an abstraction where we show there is an "online team repository", online "forks" and local "clones". One could highlight "syncing" between repositories as a key concept, Another general concept would be the "commit" as way to introduce changes and a "pull request" as a barrier that allows to take advantage of githubs "review"/commenting capabilities as well as "continuous integration". The "release" is another key concept that probably requires that we show  two branches "develop" and "master" like e.g. in http://nvie.com/img/main-branches@2x.png 
Its bascially everything in the plot - I would just arrange it a bit different.

I will try to come up with a quick example plot to show what I mean ;)

**Comment by ypriverol** [comment]
@timosachsenberg please can you include some of this ideas in the current version of the figure, because in any case it is a svg and you should be able to modify it easily using http://editor.method.ac/

**Comment by lgatto** [comment]
@timosachsenberg +1

**Comment by julianu** [comment]
also @timosachsenberg +1
Actually, something like the visualization you send with some of the community interaction would probably be the best. Let me now, whether you find the time to change the current image accordingly, otherwise I will give it another try in the next days.

**Comment by timosachsenberg** [comment]
I will try to create a quick mockup that we might want to trim down or simplify.

**Comment by timosachsenberg** [comment]
What about this variant (its just a mockup)? Its more technical in some parts, in others its simpler.

image2

**Comment by julianu** [comment]
That looks nice :+1: 
Only needs some small changes now, like two times release 1.0.0 .

**Comment by lgatto** [comment]
+1

**Comment by ypriverol** [comment]
Getting there!!! +1

**Comment by timosachsenberg** [comment]
Another iteration.

image3

**Comment by timosachsenberg** [comment]
forgot the 1.0.1 tag - will fix if we agree on a version.

**Comment by ypriverol** [comment]
I really like this one. +1

**Comment by timosachsenberg** [comment]
Ok I polished it a bit. Some symbols are not ideal but I am happy with this one.

github_paper

**Comment by ypriverol** [comment]
@timosachsenberg +1 I will merge this with the current version if you are agree

**Comment by timosachsenberg** [comment]
its a png right now... do you want the svg?

**Comment by ypriverol** [comment]
I would prefer a proper svg to be able to edited

**Comment by timosachsenberg** [comment]
here it is https://gist.github.com/timosachsenberg/23201d9dadfeecea7ee5

**Comment by ypriverol** [comment]
Ask for the pull-request and I will do the merge

**Pull request closed without merging**
