### PR TITLE
first draft of figure

### PR DESCRIPTION
**Pull request by julianu**
please give feedback

### CODE REVIEW

**Comment by ypriverol** [comment]
@julianu The figure look a bit chaotic and difficult to follow.

1- some of the components of the figure will need a alignment, for example: bob,  bob fork, and commit to fork.

2- The big circule is a bit empty compare with the small circule, perhaps you can earn some space for the small circle and reduce the empty space in the big circle. 

3- Perhaps the circle between bob->fork->commit->pullrequest-tests can be link using arrows given the idea of a complete cycle.   

This are some of my comments.

**Comment by julianu** [comment]
Alignment and some re-positioning is obviously necessary, yes.
Before doing these, I just wanted to know, whether the general direction is ok.

I will wait for further comments until tomorrow.

**Comment by ypriverol** [comment]
The general idea is more than fine for me, any complains @timosachsenberg @lgatto. In my opinion some ideas are also missing, it needs to be clear what we are explaining about the commits, merge, etc the life cycle of the github project. One thing is missing is the communication between the members of the projects, issues, etc. you can take this picture as the core and then zoom for some of the concepts, what do you think?

**Comment by timosachsenberg** [comment]
I like the idea. I agree with Yasset that we might want to lay out the concepts more clearly.
I think we should also emphasize on the interaction/communication and highlight them with e.g. arrows so that we get something remotly related to a picture like this: http://www.sintelix.com/graphics/InfoEx-interactions.png

Github:
- development cycle (forking, coding, PR, testing, deployment/release)
- communication between developers (issues, wiki, gitter, ...), show team/organization + external contributors similar to how you did
- communication with users (issues, wiki, gitter, etc.)
- entry point (homepage e.g. hosted on github)

Scientific Community:
- I like the "overlap" idea. Here you already have something like the interaction arrows...

If this gets to large we might think of zooming in into e.g. the development cycle etc.

**Comment by lgatto** [comment]
I agree with all points highlighted so far. My priority would be for the non-technical aspects (these are covered by GitHub themselves), but for the **open social aspects** of using GitHub: development team (branches, CI, ...), users (issues), other developers (forking, PR) and wider community (github pages, wiki, issues), ...

**Comment by ypriverol** [comment]
Agree with @lgatto and I will merge the current branch and way for the next version @julianu

**Pull request closed without merging**
